<?php $this->layout('layout::layout', ['title' => 'Test']) ?>
<header>
<h2>
  Welcome!
</h2>
</header>    
      
<nav class="app-navbar">
  <ul>
    <li><a href="#">Home</a></li>
    <li><a href="#">Buy Now!</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Gift Ideas</a></li>
  </ul>
</nav>
<section id="intro">
  <p>
  Welcome to <strong>StarTrackr!</strong> the planet's premier celebrity tracking and monitoring service. Need to know where in the world the best bands, musicians or producers are within 2.2 square meters? You've come to the right place. We have a very special special on B-grade celebs this week, so hurry in!    
  </p>
  <div id="disclaimer" class="alert alert-warning alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">Disclaimer!</h4>
    <p class="mb-0">
      This service is not intended for the those with criminal intent. 
      Celebrities are kind of like people so their privacy should be respected.
    </p>
    <button type="button" class="close" data-dismiss="alert" aria-label="Sulje">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</section>

<section id="news">
  <h2>Latest News</h2>
  <p>
    Which member of the seminal calypso/lectro band <em>C&amp;C Music Sweatshop</em> was spotted last night at <em>Dirt</em>, the trendy New York restaurant that serves only food caught and retrieved by the chef's own hands?
    <span class="spoiler">Yes! It's the ever-effervescent, <em>Glendatronix</em>!</span>
  </p>
  <p>Who lost their recording contract today? <span class="spoiler">The Zaxntines!</span></p>
</section>

<section>
  <h2 class="heading">Our Celebrities</h2>
  <p class="info">
  We have an ever changing roster of newly chipped celebrities. But it can take as little as a week for the little critters to realise they've been tagged - so you have to be fast! 
  </p>
  <div class="table-responsive-sm">
  <table class="table table-sm table-hover table-striped data" id="celebs">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Occupation</th>
        <th scope="col">Approx. Location</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">203A</th>
          <td>Johny Stardust (<a href="bio.pdf">bio</a>)</td>
          <td>Front-man</td>
          <td>Los Angeles</td>
          <td>$39.95</td>
      </tr>
      <tr>
        <th scope="row">141B</th>
        <td>Beau Dandy (<a href="img.jpg">pic</a>,<a href="bio.pdf">bio</a>)</td>
        <td>Singer</td>
        <td>New York</td>
        <td>$39.95</td>
      </tr>
      <tr>
        <th scope="row">2031</th>
        <td>Mo' Fat (<a href="img.jpg">pic</a>)</td>
        <td>Producer</td>
        <td>New York</td>
        <td>$19.95</td>
      </tr>
      <tr>
        <th scope="row">007F</th>
        <td>Kellie Kelly (<a href="bio.pdf">bio</a>,<a href="w.doc">press</a>)</td>
        <td>Singer</td>
        <td>Omaha</td>
        <td>$11.95</td>
      </tr>
      <tr>
        <th scope="row">8A05</th>
        <td>Darth Fader (<a href="img.jpg">pic</a>)</td>
        <td>DJ</td>
        <td>London</td>
        <td>$19.95</td>
      </tr>
      <tr>
        <th scope="row">6636</th>
        <td>Glendatronix  (<a href="bio.pdf">bio</a>,<a href="w.doc">press</a>)</td>
        <td>Keytarist</td>
        <td>London</td>
        <td>$39.95</td>
      </tr>
    </tbody>
  </table>
  </div>
</section>
      
<section id="comment">
  <h2>Leave a comment</h2>
  name:<br />
  <input type="text" /><br/>
  comment:<br/>
  <textarea rows="5" cols="30" name="comment"></textarea>
</section>
      
<h2>Fine Print</h2>
<p id="fine_print">
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.    
</p>
