<nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Brand -->
      <a class="navbar-brand" href="/">
        <img src="https://framework.zend.com/images/logos/zf-logo-mark.png" alt="Zend Expressive" height="28" />
      </a>
    </div>
    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="https://docs.zendframework.com/zend-expressive" target="_blank" class="nav-link">
            <i class="fa fa-book"></i> Docs
          </a>
        </li>

        <li class="nav-item">
          <a href="https://github.com/zendframework/zend-expressive" target="_blank" class="nav-link">
            <i class="fa fa-wrench"></i> Contribute
          </a>
        </li>
        
        <li class="nav-item">
          <a href="/api/ping" class="nav-link">
            Ping Test
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>